[project]
name = "algorithm-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "docling>=2.30.0",
    "isort>=6.0.1",
]
